redis:
  image: redis:3
  ports:
    - "6379:6379"
amcuiserver:
  build: .
  command: bash -c "while true; do sleep 3; grunt serve; done"
  working_dir: /amc
  volumes:
    - ./app:/amc/app
  ports:
    - "8181:8181"
    - "5858:5858"
    - "9001:9001"
  links:
    - redis:redis