amcuiserver:
  build: .
  command: bash -c "while true; do sleep 3; grunt serve; done" 
  working_dir: /amc
  volumes:
    - ./app:/amc/app
  ports:
    - "8181:8181"
    - "5858:5858"
    - "9001:9001"
    