redis:
  image: redis:3
  restart: always
  volumes:
    - ./data:/data
amcuiserver:
  build: .
  env_file: .production.env
  working_dir: /amc
  restart: always
  volumes:
    - ./dist/public:/amc/dist/public
    - ./projects:/amc/projects
  ports:
    - "127.0.0.1:9002:9001"
  links:
    - redis:redis